test_name: Check taxes

stages:
  - name: Test petrol
    request:
      url: http://localhost:5000/companyCarTaxes/petrol/25
      method: GET
    response:
      status_code: 200
      body:
        fuel: petrol
        maxCo2: 50
        taxRate: 0.8

  - name: Test boundaries
    request:
      url: http://localhost:5000/companyCarTaxes/petrol/150
      method: GET
    response:
      status_code: 200
      body:
        taxRate: 1.3

  - name: Test electric cars
    request:
      url: http://localhost:5000/companyCarTaxes/electric/0
      method: GET
    response:
      status_code: 200
      body:
        taxRate: 0.5

  - name: Check CO2 emission upper bound
    request:
      url: http://localhost:5000/companyCarTaxes/diesel/300
      method: GET
    response:
      status_code: 200
      body:
        minCo2: 150
        taxRate: 1.8